name: Deploy Vless
on:
  schedule:
    - cron:  '0 * * * *'
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@master
        with:
          repository: cmliu/edgetunnel
          token: ${{ secrets.GH_PAT }}

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./
