name: Deploy Vless
on:
  schedule:
    - cron:  '0 * * * *'
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        run: |
          git clone git@github.com:cmliu/edgetunnel.git

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./edgetunnel
