name: Deploy Vless
on:
  schedule:
    - cron:  '0 * * * *'
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@master
        with:
          repository: cmliu/edgetunnel
          token: ${{ secrets.GH_PAT }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Deploy
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          npm install wrangler --save-dev
          last_commit=$(git log -1 --format=%cd --date=unix)
          current_time=$(date +%s)
          time_difference=$(( (current_time - last_commit) / 3600 ))
          if [ $time_difference -lt 1 ]; then
              npx wrangler pages deploy --project-name vless ./
          fi
